"""empty message

Revision ID: df5513addac9
Revises: 4253263d40c9
Create Date: 2020-02-21 21:45:29.577909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5513addac9'
down_revision = '4253263d40c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
